### PR TITLE
implement padStart

### LINKED ISSUE #19: Implement String.prototype.padStart
Implement a polyfill for String.prototype.padStart as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart#Polyfill

### PR DESCRIPTION
**Pull request by rixlabs**
Resolve #19  implement padStart

### CODE REVIEW

**Comment by msn0** [comment]
There's something wrong with the commit author's email. Github treats you as unrecognised author and your contribution wont count. Please fix if possible.

**Comment by rixlabs** [comment]
sorry I'm at work and I have other global config. give me a minute

**Comment by rixlabs** [comment]
better?

**Comment by msn0** [comment]
Great :)

I'll look into it later. This evening most probably.

**Pull request merged**
